feat(storybook): add tooltip bubble docs
deven-org/B01LER-Kitchen pull request #821
Opened 2024-01-23 13:04 UTC by bar-tay

2024-01-23 14:33 UTC, thrbnhrtmnn requested changes
Left a comment [here](https://github.com/deven-org/B01LER-Kitchen/issues/715#issuecomment-1906177657) about the correct placement of the component in the current folder structure

2024-01-23 15:56 UTC, thrbnhrtmnn approved these changes

2024-01-24 08:44 UTC, JpunktWpunkt approved these changes

2024-01-24 09:33 UTC, JpunktWpunkt submitted a review, later dismissed

2024-01-24 09:40 UTC, thrbnhrtmnn requested changes
The link to the tooltip bubble under Dependencies broke. Once fixed this can be approved.

2024-01-24 10:05 UTC, thrbnhrtmnn submitted a review, later dismissed

2024-01-24 10:25 UTC, JpunktWpunkt submitted a review, later dismissed

2024-01-24 10:30 UTC, JpunktWpunkt submitted a review, later dismissed

2024-01-24 10:47 UTC, thrbnhrtmnn approved these changes

2024-01-24 12:33 UTC, thrbnhrtmnn approved these changes

2024-01-24 12:47 UTC, JpunktWpunkt approved these changes

2024-01-24 12:48 UTC, merged